//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Purchase
    {
        public int Id { get; set; }
        public string Products { get; set; }
        public int Amount { get; set; }
        public string Status { get; set; }
        public string Date { get; set; }
        public string Owner { get; set; }
    
        public virtual User User { get; set; }
    }
}
