//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [MetadataType(typeof(Usermetadata))]
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
            this.Sale_Purchase = new HashSet<Sale_Purchase>();
        }
    
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string phoneNo { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Sale_Purchase> Sale_Purchase { get; set; }
    }
}
